[alias]
xtask = "run --package xtask --"

[build]
rustflags = ["--cfg", "tokio_unstable"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["--cfg", "tokio_unstable"]

[target.x86_64-unknown-linux-musl]
rustflags = ["--cfg", "tokio_unstable"]
